/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../../../index";

/**
 * Challenge solution
 */
export type ChallengeSolveRequestBodyDtoSolution =
    | ElsiKoraApi.ChallengeSolveRequestBodyDtoSolution.Click
    | ElsiKoraApi.ChallengeSolveRequestBodyDtoSolution.Pow;

export namespace ChallengeSolveRequestBodyDtoSolution {
    export interface Click extends ElsiKoraApi.ChallengeUpdateBodySolutionClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeUpdateBodySolutionPowDto {
        type: "pow";
    }
}
