/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as ElsiKoraApi from "../index";

export class BadRequestError extends errors.ElsiKoraApiError {
    constructor(body: ElsiKoraApi.ExceptionBadRequestDto) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
