/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChallengeCreateResponseDataPowDto {
    /** Challenge data PoW challenge */
    challenge?: string;
    /** Challenge data difficulty */
    difficulty?: number;
}
