/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge data
 */
export type ChallengeUpdateResponseDtoData =
    | ElsiKoraApi.ChallengeUpdateResponseDtoData.Click
    | ElsiKoraApi.ChallengeUpdateResponseDtoData.Pow;

export namespace ChallengeUpdateResponseDtoData {
    export interface Click extends ElsiKoraApi.ChallengeUpdateResponseDataClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeUpdateResponseDataPowDto {
        type: "pow";
    }
}
