/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge data
 */
export type ChallengeUpdateBodyDtoData =
    | ElsiKoraApi.ChallengeUpdateBodyDtoData.Click
    | ElsiKoraApi.ChallengeUpdateBodyDtoData.Pow;

export namespace ChallengeUpdateBodyDtoData {
    export interface Click extends ElsiKoraApi.ChallengeUpdateBodyDataClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeUpdateBodyDataPowDto {
        type: "pow";
    }
}
