/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Challenge type
 */
export type ChallengeGetResponseDtoType = "click" | "pow";
export const ChallengeGetResponseDtoType = {
    Click: "click",
    Pow: "pow",
} as const;
