/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge solution
 */
export type ChallengeUpdateResponseDtoSolution =
    | ElsiKoraApi.ChallengeUpdateResponseDtoSolution.Click
    | ElsiKoraApi.ChallengeUpdateResponseDtoSolution.Pow;

export namespace ChallengeUpdateResponseDtoSolution {
    export interface Click extends ElsiKoraApi.ChallengeUpdateResponseSolutionClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeUpdateResponseSolutionPowDto {
        type: "pow";
    }
}
