/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge solution
 */
export type ChallengeUpdateBodyDtoSolution =
    | ElsiKoraApi.ChallengeUpdateBodyDtoSolution.Click
    | ElsiKoraApi.ChallengeUpdateBodyDtoSolution.Pow;

export namespace ChallengeUpdateBodyDtoSolution {
    export interface Click extends ElsiKoraApi.ChallengeUpdateBodySolutionClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeUpdateBodySolutionPowDto {
        type: "pow";
    }
}
