/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

export interface ChallengeSolveResponseBodyDto {
    /** Challenge data */
    data?: ElsiKoraApi.ChallengeSolveResponseBodyDtoData;
    /** Challenge solution token */
    token?: string;
}
