/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

export interface ChallengeCreateResponseDto {
    /** Challenge creation date */
    createdAt?: Date;
    /** Challenge data */
    data?: ElsiKoraApi.ChallengeCreateResponseDtoData;
    /** Challenge identifier */
    id?: string;
    /** Challenge solved state */
    isSolved?: boolean;
    /** Challenge solution */
    solution?: ElsiKoraApi.ChallengeCreateResponseDtoSolution;
    /** Challenge solution token */
    token?: string;
    /** Challenge type */
    type?: ElsiKoraApi.ChallengeCreateResponseDtoType;
    /** Challenge last update date */
    updatedAt?: Date;
    /** Challenge client */
    client?: ElsiKoraApi.ChallengeCreateResponseClientDto;
}
