/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

export interface ChallengeUpdateBodyDto {
    /** Challenge data */
    data: ElsiKoraApi.ChallengeUpdateBodyDtoData;
    /** Challenge solved state */
    isSolved: boolean;
    /** Challenge solution */
    solution: ElsiKoraApi.ChallengeUpdateBodyDtoSolution;
    /** Challenge solution token */
    token: string;
    /** Challenge type */
    type: ElsiKoraApi.ChallengeUpdateBodyDtoType;
    /** Challenge client */
    client: string;
}
