/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

export interface ChallengeUpdateResponseDto {
    /** Challenge creation date */
    createdAt?: Date;
    /** Challenge data */
    data?: ElsiKoraApi.ChallengeUpdateResponseDtoData;
    /** Challenge identifier */
    id?: string;
    /** Challenge solved state */
    isSolved?: boolean;
    /** Challenge solution */
    solution?: ElsiKoraApi.ChallengeUpdateResponseDtoSolution;
    /** Challenge solution token */
    token?: string;
    /** Challenge type */
    type?: ElsiKoraApi.ChallengeUpdateResponseDtoType;
    /** Challenge last update date */
    updatedAt?: Date;
    /** Challenge client */
    client?: ElsiKoraApi.ChallengeUpdateResponseClientDto;
}
