/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge solution
 */
export type ChallengeGetResponseDtoSolution =
    | ElsiKoraApi.ChallengeGetResponseDtoSolution.Click
    | ElsiKoraApi.ChallengeGetResponseDtoSolution.Pow;

export namespace ChallengeGetResponseDtoSolution {
    export interface Click extends ElsiKoraApi.ChallengeGetResponseSolutionClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeGetResponseSolutionPowDto {
        type: "pow";
    }
}
