/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge solution
 */
export type ChallengeCreateResponseDtoSolution =
    | ElsiKoraApi.ChallengeCreateResponseDtoSolution.Click
    | ElsiKoraApi.ChallengeCreateResponseDtoSolution.Pow;

export namespace ChallengeCreateResponseDtoSolution {
    export interface Click extends ElsiKoraApi.ChallengeCreateResponseSolutionClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeCreateResponseSolutionPowDto {
        type: "pow";
    }
}
