/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChallengeCreateResponseSolutionPowDto {
    /** Challenge solution PoW hash */
    hash?: string;
    /** Challenge solution PoW nonce */
    nonce?: string;
}
