/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge data
 */
export type ChallengeGetResponseDtoData =
    | ElsiKoraApi.ChallengeGetResponseDtoData.Click
    | ElsiKoraApi.ChallengeGetResponseDtoData.Pow;

export namespace ChallengeGetResponseDtoData {
    export interface Click extends ElsiKoraApi.ChallengeGetResponseDataClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeGetResponseDataPowDto {
        type: "pow";
    }
}
