/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Challenge type
 */
export type ChallengeUpdateResponseDtoType = "click" | "pow";
export const ChallengeUpdateResponseDtoType = {
    Click: "click",
    Pow: "pow",
} as const;
