/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../index";

/**
 * Challenge data
 */
export type ChallengeSolveResponseBodyDtoData =
    | ElsiKoraApi.ChallengeSolveResponseBodyDtoData.Click
    | ElsiKoraApi.ChallengeSolveResponseBodyDtoData.Pow;

export namespace ChallengeSolveResponseBodyDtoData {
    export interface Click extends ElsiKoraApi.ChallengeGetResponseDataClickDto {
        type: "click";
    }

    export interface Pow extends ElsiKoraApi.ChallengeGetResponseDataPowDto {
        type: "pow";
    }
}
