/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExceptionNotFoundDto {
    /** Correlation identifier */
    correlationId?: string;
    /** Error name */
    error?: string;
    /** Error message */
    message?: string;
    /** Error status code */
    statusCode?: number;
    /** Error timestamp */
    timestamp?: number;
}
