/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeGetResponseSolutionClickDto } from "./ChallengeGetResponseSolutionClickDto";
import { ChallengeGetResponseSolutionPowDto } from "./ChallengeGetResponseSolutionPowDto";

export const ChallengeGetResponseDtoSolution: core.serialization.Schema<
    serializers.ChallengeGetResponseDtoSolution.Raw,
    ElsiKoraApi.ChallengeGetResponseDtoSolution
> = core.serialization
    .union("type", {
        click: ChallengeGetResponseSolutionClickDto,
        pow: ChallengeGetResponseSolutionPowDto,
    })
    .transform<ElsiKoraApi.ChallengeGetResponseDtoSolution>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeGetResponseDtoSolution {
    export type Raw = ChallengeGetResponseDtoSolution.Click | ChallengeGetResponseDtoSolution.Pow;

    export interface Click extends ChallengeGetResponseSolutionClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeGetResponseSolutionPowDto.Raw {
        type: "pow";
    }
}
