/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeGetResponseDtoData } from "./ChallengeGetResponseDtoData";
import { ChallengeGetResponseDtoSolution } from "./ChallengeGetResponseDtoSolution";
import { ChallengeGetResponseDtoType } from "./ChallengeGetResponseDtoType";
import { ChallengeGetResponseClientDto } from "./ChallengeGetResponseClientDto";

export const ChallengeGetResponseDto: core.serialization.ObjectSchema<
    serializers.ChallengeGetResponseDto.Raw,
    ElsiKoraApi.ChallengeGetResponseDto
> = core.serialization.object({
    createdAt: core.serialization.date().optional(),
    data: ChallengeGetResponseDtoData.optional(),
    id: core.serialization.string().optional(),
    isSolved: core.serialization.boolean().optional(),
    solution: ChallengeGetResponseDtoSolution.optional(),
    token: core.serialization.string().optional(),
    type: ChallengeGetResponseDtoType.optional(),
    updatedAt: core.serialization.date().optional(),
    client: ChallengeGetResponseClientDto.optional(),
});

export declare namespace ChallengeGetResponseDto {
    export interface Raw {
        createdAt?: string | null;
        data?: ChallengeGetResponseDtoData.Raw | null;
        id?: string | null;
        isSolved?: boolean | null;
        solution?: ChallengeGetResponseDtoSolution.Raw | null;
        token?: string | null;
        type?: ChallengeGetResponseDtoType.Raw | null;
        updatedAt?: string | null;
        client?: ChallengeGetResponseClientDto.Raw | null;
    }
}
