/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeGetResponseDataClickDto } from "./ChallengeGetResponseDataClickDto";
import { ChallengeGetResponseDataPowDto } from "./ChallengeGetResponseDataPowDto";

export const ChallengeSolveResponseBodyDtoData: core.serialization.Schema<
    serializers.ChallengeSolveResponseBodyDtoData.Raw,
    ElsiKoraApi.ChallengeSolveResponseBodyDtoData
> = core.serialization
    .union("type", {
        click: ChallengeGetResponseDataClickDto,
        pow: ChallengeGetResponseDataPowDto,
    })
    .transform<ElsiKoraApi.ChallengeSolveResponseBodyDtoData>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeSolveResponseBodyDtoData {
    export type Raw = ChallengeSolveResponseBodyDtoData.Click | ChallengeSolveResponseBodyDtoData.Pow;

    export interface Click extends ChallengeGetResponseDataClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeGetResponseDataPowDto.Raw {
        type: "pow";
    }
}
