/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeGetBodyclientDto: core.serialization.ObjectSchema<
    serializers.ChallengeGetBodyclientDto.Raw,
    ElsiKoraApi.ChallengeGetBodyclientDto
> = core.serialization.object({});

export declare namespace ChallengeGetBodyclientDto {
    export interface Raw {}
}
