/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodyclientDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodyclientDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodyclientDto
> = core.serialization.object({});

export declare namespace ChallengeUpdateBodyclientDto {
    export interface Raw {}
}
