/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeUpdateBodySolutionClickDto } from "./ChallengeUpdateBodySolutionClickDto";
import { ChallengeUpdateBodySolutionPowDto } from "./ChallengeUpdateBodySolutionPowDto";

export const ChallengeUpdateBodyDtoSolution: core.serialization.Schema<
    serializers.ChallengeUpdateBodyDtoSolution.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDtoSolution
> = core.serialization
    .union("type", {
        click: ChallengeUpdateBodySolutionClickDto,
        pow: ChallengeUpdateBodySolutionPowDto,
    })
    .transform<ElsiKoraApi.ChallengeUpdateBodyDtoSolution>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeUpdateBodyDtoSolution {
    export type Raw = ChallengeUpdateBodyDtoSolution.Click | ChallengeUpdateBodyDtoSolution.Pow;

    export interface Click extends ChallengeUpdateBodySolutionClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeUpdateBodySolutionPowDto.Raw {
        type: "pow";
    }
}
