/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeGetResponseDtoType: core.serialization.Schema<
    serializers.ChallengeGetResponseDtoType.Raw,
    ElsiKoraApi.ChallengeGetResponseDtoType
> = core.serialization.enum_(["click", "pow"]);

export declare namespace ChallengeGetResponseDtoType {
    export type Raw = "click" | "pow";
}
