/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeUpdateBodyDtoData } from "./ChallengeUpdateBodyDtoData";
import { ChallengeUpdateBodyDtoSolution } from "./ChallengeUpdateBodyDtoSolution";
import { ChallengeUpdateBodyDtoType } from "./ChallengeUpdateBodyDtoType";

export const ChallengeUpdateBodyDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodyDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDto
> = core.serialization.object({
    data: ChallengeUpdateBodyDtoData,
    isSolved: core.serialization.boolean(),
    solution: ChallengeUpdateBodyDtoSolution,
    token: core.serialization.string(),
    type: ChallengeUpdateBodyDtoType,
    client: core.serialization.string(),
});

export declare namespace ChallengeUpdateBodyDto {
    export interface Raw {
        data: ChallengeUpdateBodyDtoData.Raw;
        isSolved: boolean;
        solution: ChallengeUpdateBodyDtoSolution.Raw;
        token: string;
        type: ChallengeUpdateBodyDtoType.Raw;
        client: string;
    }
}
