/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeCreateResponseSolutionClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeCreateResponseSolutionClickDto.Raw,
    ElsiKoraApi.ChallengeCreateResponseSolutionClickDto
> = core.serialization.object({});

export declare namespace ChallengeCreateResponseSolutionClickDto {
    export interface Raw {}
}
