/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodyDtoType: core.serialization.Schema<
    serializers.ChallengeUpdateBodyDtoType.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDtoType
> = core.serialization.enum_(["click", "pow"]);

export declare namespace ChallengeUpdateBodyDtoType {
    export type Raw = "click" | "pow";
}
