/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeUpdateResponseDataClickDto } from "./ChallengeUpdateResponseDataClickDto";
import { ChallengeUpdateResponseDataPowDto } from "./ChallengeUpdateResponseDataPowDto";

export const ChallengeUpdateResponseDtoData: core.serialization.Schema<
    serializers.ChallengeUpdateResponseDtoData.Raw,
    ElsiKoraApi.ChallengeUpdateResponseDtoData
> = core.serialization
    .union("type", {
        click: ChallengeUpdateResponseDataClickDto,
        pow: ChallengeUpdateResponseDataPowDto,
    })
    .transform<ElsiKoraApi.ChallengeUpdateResponseDtoData>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeUpdateResponseDtoData {
    export type Raw = ChallengeUpdateResponseDtoData.Click | ChallengeUpdateResponseDtoData.Pow;

    export interface Click extends ChallengeUpdateResponseDataClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeUpdateResponseDataPowDto.Raw {
        type: "pow";
    }
}
