/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateResponseSolutionPowDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateResponseSolutionPowDto.Raw,
    ElsiKoraApi.ChallengeUpdateResponseSolutionPowDto
> = core.serialization.object({
    hash: core.serialization.string().optional(),
    nonce: core.serialization.string().optional(),
});

export declare namespace ChallengeUpdateResponseSolutionPowDto {
    export interface Raw {
        hash?: string | null;
        nonce?: string | null;
    }
}
