/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeUpdateResponseSolutionClickDto } from "./ChallengeUpdateResponseSolutionClickDto";
import { ChallengeUpdateResponseSolutionPowDto } from "./ChallengeUpdateResponseSolutionPowDto";

export const ChallengeUpdateResponseDtoSolution: core.serialization.Schema<
    serializers.ChallengeUpdateResponseDtoSolution.Raw,
    ElsiKoraApi.ChallengeUpdateResponseDtoSolution
> = core.serialization
    .union("type", {
        click: ChallengeUpdateResponseSolutionClickDto,
        pow: ChallengeUpdateResponseSolutionPowDto,
    })
    .transform<ElsiKoraApi.ChallengeUpdateResponseDtoSolution>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeUpdateResponseDtoSolution {
    export type Raw = ChallengeUpdateResponseDtoSolution.Click | ChallengeUpdateResponseDtoSolution.Pow;

    export interface Click extends ChallengeUpdateResponseSolutionClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeUpdateResponseSolutionPowDto.Raw {
        type: "pow";
    }
}
