/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeCreateResponseClientDto: core.serialization.ObjectSchema<
    serializers.ChallengeCreateResponseClientDto.Raw,
    ElsiKoraApi.ChallengeCreateResponseClientDto
> = core.serialization.object({
    id: core.serialization.string().optional(),
});

export declare namespace ChallengeCreateResponseClientDto {
    export interface Raw {
        id?: string | null;
    }
}
