/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeCreateResponseDtoData } from "./ChallengeCreateResponseDtoData";
import { ChallengeCreateResponseDtoSolution } from "./ChallengeCreateResponseDtoSolution";
import { ChallengeCreateResponseDtoType } from "./ChallengeCreateResponseDtoType";
import { ChallengeCreateResponseClientDto } from "./ChallengeCreateResponseClientDto";

export const ChallengeCreateResponseDto: core.serialization.ObjectSchema<
    serializers.ChallengeCreateResponseDto.Raw,
    ElsiKoraApi.ChallengeCreateResponseDto
> = core.serialization.object({
    createdAt: core.serialization.date().optional(),
    data: ChallengeCreateResponseDtoData.optional(),
    id: core.serialization.string().optional(),
    isSolved: core.serialization.boolean().optional(),
    solution: ChallengeCreateResponseDtoSolution.optional(),
    token: core.serialization.string().optional(),
    type: ChallengeCreateResponseDtoType.optional(),
    updatedAt: core.serialization.date().optional(),
    client: ChallengeCreateResponseClientDto.optional(),
});

export declare namespace ChallengeCreateResponseDto {
    export interface Raw {
        createdAt?: string | null;
        data?: ChallengeCreateResponseDtoData.Raw | null;
        id?: string | null;
        isSolved?: boolean | null;
        solution?: ChallengeCreateResponseDtoSolution.Raw | null;
        token?: string | null;
        type?: ChallengeCreateResponseDtoType.Raw | null;
        updatedAt?: string | null;
        client?: ChallengeCreateResponseClientDto.Raw | null;
    }
}
