/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodySolutionPowDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodySolutionPowDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodySolutionPowDto
> = core.serialization.object({
    hash: core.serialization.string(),
    nonce: core.serialization.string(),
});

export declare namespace ChallengeUpdateBodySolutionPowDto {
    export interface Raw {
        hash: string;
        nonce: string;
    }
}
