/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateResponseSolutionClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateResponseSolutionClickDto.Raw,
    ElsiKoraApi.ChallengeUpdateResponseSolutionClickDto
> = core.serialization.object({
    data: core.serialization.boolean().optional(),
});

export declare namespace ChallengeUpdateResponseSolutionClickDto {
    export interface Raw {
        data?: boolean | null;
    }
}
