/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodyDataClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodyDataClickDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDataClickDto
> = core.serialization.object({
    challenge: core.serialization.boolean(),
});

export declare namespace ChallengeUpdateBodyDataClickDto {
    export interface Raw {
        challenge: boolean;
    }
}
