/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeVerifyResponseBodyDto: core.serialization.ObjectSchema<
    serializers.ChallengeVerifyResponseBodyDto.Raw,
    ElsiKoraApi.ChallengeVerifyResponseBodyDto
> = core.serialization.object({
    isSolved: core.serialization.boolean().optional(),
});

export declare namespace ChallengeVerifyResponseBodyDto {
    export interface Raw {
        isSolved?: boolean | null;
    }
}
