/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateResponseDtoType: core.serialization.Schema<
    serializers.ChallengeUpdateResponseDtoType.Raw,
    ElsiKoraApi.ChallengeUpdateResponseDtoType
> = core.serialization.enum_(["click", "pow"]);

export declare namespace ChallengeUpdateResponseDtoType {
    export type Raw = "click" | "pow";
}
