/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeCreateResponseSolutionClickDto } from "./ChallengeCreateResponseSolutionClickDto";
import { ChallengeCreateResponseSolutionPowDto } from "./ChallengeCreateResponseSolutionPowDto";

export const ChallengeCreateResponseDtoSolution: core.serialization.Schema<
    serializers.ChallengeCreateResponseDtoSolution.Raw,
    ElsiKoraApi.ChallengeCreateResponseDtoSolution
> = core.serialization
    .union("type", {
        click: ChallengeCreateResponseSolutionClickDto,
        pow: ChallengeCreateResponseSolutionPowDto,
    })
    .transform<ElsiKoraApi.ChallengeCreateResponseDtoSolution>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeCreateResponseDtoSolution {
    export type Raw = ChallengeCreateResponseDtoSolution.Click | ChallengeCreateResponseDtoSolution.Pow;

    export interface Click extends ChallengeCreateResponseSolutionClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeCreateResponseSolutionPowDto.Raw {
        type: "pow";
    }
}
