/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeGetResponseSolutionClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeGetResponseSolutionClickDto.Raw,
    ElsiKoraApi.ChallengeGetResponseSolutionClickDto
> = core.serialization.object({
    data: core.serialization.boolean().optional(),
});

export declare namespace ChallengeGetResponseSolutionClickDto {
    export interface Raw {
        data?: boolean | null;
    }
}
