/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeCreateBodyclientDto: core.serialization.ObjectSchema<
    serializers.ChallengeCreateBodyclientDto.Raw,
    ElsiKoraApi.ChallengeCreateBodyclientDto
> = core.serialization.object({});

export declare namespace ChallengeCreateBodyclientDto {
    export interface Raw {}
}
