/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeUpdateBodyDataClickDto } from "./ChallengeUpdateBodyDataClickDto";
import { ChallengeUpdateBodyDataPowDto } from "./ChallengeUpdateBodyDataPowDto";

export const ChallengeUpdateBodyDtoData: core.serialization.Schema<
    serializers.ChallengeUpdateBodyDtoData.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDtoData
> = core.serialization
    .union("type", {
        click: ChallengeUpdateBodyDataClickDto,
        pow: ChallengeUpdateBodyDataPowDto,
    })
    .transform<ElsiKoraApi.ChallengeUpdateBodyDtoData>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeUpdateBodyDtoData {
    export type Raw = ChallengeUpdateBodyDtoData.Click | ChallengeUpdateBodyDtoData.Pow;

    export interface Click extends ChallengeUpdateBodyDataClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeUpdateBodyDataPowDto.Raw {
        type: "pow";
    }
}
