/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeCreateResponseDtoType: core.serialization.Schema<
    serializers.ChallengeCreateResponseDtoType.Raw,
    ElsiKoraApi.ChallengeCreateResponseDtoType
> = core.serialization.enum_(["click", "pow"]);

export declare namespace ChallengeCreateResponseDtoType {
    export type Raw = "click" | "pow";
}
