/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateRequestDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateRequestDto.Raw,
    ElsiKoraApi.ChallengeUpdateRequestDto
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace ChallengeUpdateRequestDto {
    export interface Raw {
        id: string;
    }
}
