/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeSolveResponseBodyDtoData } from "./ChallengeSolveResponseBodyDtoData";

export const ChallengeSolveResponseBodyDto: core.serialization.ObjectSchema<
    serializers.ChallengeSolveResponseBodyDto.Raw,
    ElsiKoraApi.ChallengeSolveResponseBodyDto
> = core.serialization.object({
    data: ChallengeSolveResponseBodyDtoData.optional(),
    token: core.serialization.string().optional(),
});

export declare namespace ChallengeSolveResponseBodyDto {
    export interface Raw {
        data?: ChallengeSolveResponseBodyDtoData.Raw | null;
        token?: string | null;
    }
}
