/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeCreateResponseDataClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeCreateResponseDataClickDto.Raw,
    ElsiKoraApi.ChallengeCreateResponseDataClickDto
> = core.serialization.object({
    challenge: core.serialization.boolean().optional(),
});

export declare namespace ChallengeCreateResponseDataClickDto {
    export interface Raw {
        challenge?: boolean | null;
    }
}
