/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";
import { ChallengeCreateResponseDataClickDto } from "./ChallengeCreateResponseDataClickDto";
import { ChallengeCreateResponseDataPowDto } from "./ChallengeCreateResponseDataPowDto";

export const ChallengeCreateResponseDtoData: core.serialization.Schema<
    serializers.ChallengeCreateResponseDtoData.Raw,
    ElsiKoraApi.ChallengeCreateResponseDtoData
> = core.serialization
    .union("type", {
        click: ChallengeCreateResponseDataClickDto,
        pow: ChallengeCreateResponseDataPowDto,
    })
    .transform<ElsiKoraApi.ChallengeCreateResponseDtoData>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeCreateResponseDtoData {
    export type Raw = ChallengeCreateResponseDtoData.Click | ChallengeCreateResponseDtoData.Pow;

    export interface Click extends ChallengeCreateResponseDataClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeCreateResponseDataPowDto.Raw {
        type: "pow";
    }
}
