/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodyDataPowDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodyDataPowDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodyDataPowDto
> = core.serialization.object({
    challenge: core.serialization.string(),
    difficulty: core.serialization.number(),
});

export declare namespace ChallengeUpdateBodyDataPowDto {
    export interface Raw {
        challenge: string;
        difficulty: number;
    }
}
