/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ChallengeUpdateBodySolutionClickDto: core.serialization.ObjectSchema<
    serializers.ChallengeUpdateBodySolutionClickDto.Raw,
    ElsiKoraApi.ChallengeUpdateBodySolutionClickDto
> = core.serialization.object({
    data: core.serialization.boolean(),
});

export declare namespace ChallengeUpdateBodySolutionClickDto {
    export interface Raw {
        data: boolean;
    }
}
