/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ElsiKoraApi from "../../api/index";
import * as core from "../../core";

export const ExceptionNotFoundDto: core.serialization.ObjectSchema<
    serializers.ExceptionNotFoundDto.Raw,
    ElsiKoraApi.ExceptionNotFoundDto
> = core.serialization.object({
    correlationId: core.serialization.property("correlationID", core.serialization.string().optional()),
    error: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    statusCode: core.serialization.number().optional(),
    timestamp: core.serialization.number().optional(),
});

export declare namespace ExceptionNotFoundDto {
    export interface Raw {
        correlationID?: string | null;
        error?: string | null;
        message?: string | null;
        statusCode?: number | null;
        timestamp?: number | null;
    }
}
