/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ElsiKoraApi from "../../../../api/index";
import * as core from "../../../../core";
import { ChallengeUpdateBodySolutionClickDto } from "../../../types/ChallengeUpdateBodySolutionClickDto";
import { ChallengeUpdateBodySolutionPowDto } from "../../../types/ChallengeUpdateBodySolutionPowDto";

export const ChallengeSolveRequestBodyDtoSolution: core.serialization.Schema<
    serializers.ChallengeSolveRequestBodyDtoSolution.Raw,
    ElsiKoraApi.ChallengeSolveRequestBodyDtoSolution
> = core.serialization
    .union("type", {
        click: ChallengeUpdateBodySolutionClickDto,
        pow: ChallengeUpdateBodySolutionPowDto,
    })
    .transform<ElsiKoraApi.ChallengeSolveRequestBodyDtoSolution>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ChallengeSolveRequestBodyDtoSolution {
    export type Raw = ChallengeSolveRequestBodyDtoSolution.Click | ChallengeSolveRequestBodyDtoSolution.Pow;

    export interface Click extends ChallengeUpdateBodySolutionClickDto.Raw {
        type: "click";
    }

    export interface Pow extends ChallengeUpdateBodySolutionPowDto.Raw {
        type: "pow";
    }
}
