/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ElsiKoraApi from "../../../../index";

/**
 * @example
 *     {
 *         type: "click"
 *     }
 */
export interface ChallengeCreateBodyDto {
    /** Challenge type */
    type: ElsiKoraApi.ChallengeCreateBodyDtoType;
}
