/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         token: "44a846cc-0813-4d8d-b608-f8e8887a8b74"
 *     }
 */
export interface ChallengeVerifyRequestBodyDto {
    /** Challenge solution token */
    token: string;
}
