/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Challenge } from "./api/resources/challenge/client/Client";

export declare namespace ElsiKoraApiClient {
    export interface Options {
        environment?: core.Supplier<environments.ElsiKoraApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the X-Secret-Key header */
        secretKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Secret-Key header */
        secretKey?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class ElsiKoraApiClient {
    protected _challenge: Challenge | undefined;

    constructor(protected readonly _options: ElsiKoraApiClient.Options) {}

    public get challenge(): Challenge {
        return (this._challenge ??= new Challenge(this._options));
    }
}
