/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ElsiKoraApiEnvironment = {
    Default: "http://127.0.0.1:3000",
} as const;

export type ElsiKoraApiEnvironment = typeof ElsiKoraApiEnvironment.Default;
