/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ElsiKoraApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { ChallengeSolveRequestBodyDtoSolution } from "../../types/ChallengeSolveRequestBodyDtoSolution";

export const ChallengeSolveRequestBodyDto: core.serialization.Schema<
    serializers.ChallengeSolveRequestBodyDto.Raw,
    ElsiKoraApi.ChallengeSolveRequestBodyDto
> = core.serialization.object({
    solution: ChallengeSolveRequestBodyDtoSolution,
});

export declare namespace ChallengeSolveRequestBodyDto {
    export interface Raw {
        solution: ChallengeSolveRequestBodyDtoSolution.Raw;
    }
}
