/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ElsiKoraApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { ChallengeCreateBodyDtoType } from "../../types/ChallengeCreateBodyDtoType";

export const ChallengeCreateBodyDto: core.serialization.Schema<
    serializers.ChallengeCreateBodyDto.Raw,
    ElsiKoraApi.ChallengeCreateBodyDto
> = core.serialization.object({
    type: ChallengeCreateBodyDtoType,
});

export declare namespace ChallengeCreateBodyDto {
    export interface Raw {
        type: ChallengeCreateBodyDtoType.Raw;
    }
}
